19.03.2020 13:00:00 Подключаюсь к элементу 10.174.108.1
		   13:00:00 Не удалось авторизоваться на элементе
		   13:00:00 HTTPConnectionPool(host='10.174.108.1', port=80): Max retries exceeded with url: /cgi/lct.cgi (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f46580569b0>: Failed to establish a new connection: [Errno 111] Connection refused',))
19.03.2020 13:00:00 Подключаюсь к элементу 10.174.108.2
		   13:00:05 Подключение успешно
19.03.2020 13:00:05 Подключаюсь к элементу 10.174.108.3
		   13:00:09 Подключение успешно
19.03.2020 13:00:09 Подключаюсь к элементу 10.174.108.4
19.03.2020 13:01:36 Подключаюсь к элементу 10.174.108.1
		   13:01:36 Не удалось авторизоваться на элементе
		   13:01:36 HTTPConnectionPool(host='10.174.108.1', port=80): Max retries exceeded with url: /cgi/lct.cgi (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f17f8bab3c8>: Failed to establish a new connection: [Errno 111] Connection refused',))
19.03.2020 13:01:36 Подключаюсь к элементу 10.174.108.2
		   13:01:37 Не удалось авторизоваться на элементе
		   13:01:37 'NoneType' object has no attribute 'get'
19.03.2020 13:01:37 Подключаюсь к элементу 10.174.108.3
		   13:01:37 Не удалось авторизоваться на элементе
		   13:01:37 'NoneType' object has no attribute 'get'
19.03.2020 13:01:37 Подключаюсь к элементу 10.174.108.4
		   13:01:39 Не удалось авторизоваться на элементе
		   13:01:39 'NoneType' object has no attribute 'get'
19.03.2020 13:01:39 Подключаюсь к элементу 10.174.108.5
		   13:01:39 Не удалось авторизоваться на элементе
		   13:01:39 'NoneType' object has no attribute 'get'
19.03.2020 13:01:39 Подключаюсь к элементу 10.174.108.6
		   13:01:40 Не удалось авторизоваться на элементе
		   13:01:40 'NoneType' object has no attribute 'get'
19.03.2020 13:01:40 Подключаюсь к элементу 10.174.108.7
		   13:01:40 Не удалось авторизоваться на элементе
		   13:01:40 'NoneType' object has no attribute 'get'
19.03.2020 13:01:40 Подключаюсь к элементу 10.174.108.8
		   13:01:41 Не удалось авторизоваться на элементе
		   13:01:41 'NoneType' object has no attribute 'get'
19.03.2020 13:01:41 Подключаюсь к элементу 10.174.108.9
		   13:01:41 Не удалось авторизоваться на элементе
		   13:01:41 'NoneType' object has no attribute 'get'
19.03.2020 13:01:41 Подключаюсь к элементу 10.174.108.10
		   13:01:42 Не удалось авторизоваться на элементе
		   13:01:42 'NoneType' object has no attribute 'get'
19.03.2020 13:01:42 Подключаюсь к элементу 10.174.108.11
		   13:01:42 Не удалось авторизоваться на элементе
		   13:01:42 'NoneType' object has no attribute 'get'
19.03.2020 13:01:42 Подключаюсь к элементу 10.174.108.12
		   13:01:43 Не удалось авторизоваться на элементе
		   13:01:43 'NoneType' object has no attribute 'get'
19.03.2020 13:01:43 Подключаюсь к элементу 10.174.108.13
		   13:01:43 Не удалось авторизоваться на элементе
		   13:01:43 'NoneType' object has no attribute 'get'
19.03.2020 13:01:43 Подключаюсь к элементу 10.174.108.14
		   13:01:44 Не удалось авторизоваться на элементе
		   13:01:44 'NoneType' object has no attribute 'get'
19.03.2020 13:01:44 Подключаюсь к элементу 10.174.108.15
		   13:01:44 Не удалось авторизоваться на элементе
		   13:01:44 'NoneType' object has no attribute 'get'
19.03.2020 13:01:44 Подключаюсь к элементу 10.174.108.16
		   13:01:45 Не удалось авторизоваться на элементе
		   13:01:45 'NoneType' object has no attribute 'get'
19.03.2020 13:01:45 Подключаюсь к элементу 10.174.108.17
		   13:01:45 Не удалось авторизоваться на элементе
		   13:01:45 'NoneType' object has no attribute 'get'
19.03.2020 13:01:45 Подключаюсь к элементу 10.174.108.18
		   13:01:45 Не удалось авторизоваться на элементе
		   13:01:45 'NoneType' object has no attribute 'get'
19.03.2020 13:01:45 Подключаюсь к элементу 10.174.108.19
19.03.2020 13:01:57 Подключаюсь к элементу 10.174.108.1
		   13:01:57 Не удалось авторизоваться на элементе
		   13:01:57 HTTPConnectionPool(host='10.174.108.1', port=80): Max retries exceeded with url: /cgi/lct.cgi (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd05703a3c8>: Failed to establish a new connection: [Errno 111] Connection refused',))
19.03.2020 13:01:57 Подключаюсь к элементу 10.174.108.2
		   13:01:57 Не удалось авторизоваться на элементе
		   13:01:57 'NoneType' object has no attribute 'get'
19.03.2020 13:01:57 Подключаюсь к элементу 10.174.108.3
		   13:01:58 Не удалось авторизоваться на элементе
		   13:01:58 'NoneType' object has no attribute 'get'
19.03.2020 13:01:58 Подключаюсь к элементу 10.174.108.4
		   13:01:58 Не удалось авторизоваться на элементе
		   13:01:58 'NoneType' object has no attribute 'get'
19.03.2020 13:01:58 Подключаюсь к элементу 10.174.108.5
		   13:01:59 Не удалось авторизоваться на элементе
		   13:01:59 'NoneType' object has no attribute 'get'
19.03.2020 13:01:59 Подключаюсь к элементу 10.174.108.6
		   13:02:00 Не удалось авторизоваться на элементе
		   13:02:00 'NoneType' object has no attribute 'get'
19.03.2020 13:02:00 Подключаюсь к элементу 10.174.108.7
19.03.2020 13:03:08 Подключаюсь к элементу 10.174.108.1
		   13:03:08 Не удалось авторизоваться на элементе
		   13:03:08 HTTPConnectionPool(host='10.174.108.1', port=80): Max retries exceeded with url: /cgi/lct.cgi (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa56bbd0320>: Failed to establish a new connection: [Errno 111] Connection refused',))
19.03.2020 13:03:08 Подключаюсь к элементу 10.174.108.2
		   13:03:13 Подключение успешно
19.03.2020 13:03:13 Подключаюсь к элементу 10.174.108.3
19.03.2020 13:04:02 Подключаюсь к элементу 10.174.108.1
		   13:04:02 Не удалось авторизоваться на элементе
		   13:04:02 HTTPConnectionPool(host='10.174.108.1', port=80): Max retries exceeded with url: /cgi/lct.cgi (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa38bdf5320>: Failed to establish a new connection: [Errno 111] Connection refused',))
19.03.2020 13:04:02 Подключаюсь к элементу 10.174.108.2
		   13:04:07 Подключение успешно
19.03.2020 13:04:07 Подключаюсь к элементу 10.174.108.3
		   13:04:11 Подключение успешно
19.03.2020 13:04:11 Подключаюсь к элементу 10.174.108.4
		   13:04:18 Подключение успешно
19.03.2020 13:04:18 Подключаюсь к элементу 10.174.108.5
